obj-$(CONFIG_MACH_SUNXI50) += board.o
obj-$(CONFIG_MACH_SUNXI50) += clock.o
obj-$(CONFIG_MACH_SUNXI50) += clock_sun6i.o
obj-$(CONFIG_MACH_SUNXI50) += cpu_info.o
#obj-$(CONFIG_MACH_SUNXI50) += dram_helpers.o
obj-$(CONFIG_MACH_SUNXI50) += pinmux.o
#obj-$(CONFIG_MACH_SUNXI50) += usb_phy.o
