obj-$(CONFIG_ARM_LINUX)	+= armlinux.o
obj-$(CONFIG_BOOTM)	+= bootm.o
obj-$(CONFIG_CMD_BOOTZ)	+= bootz.o
obj-$(CONFIG_CMD_BOOTU)	+= bootu.o
obj-y	+= div0.o
obj-y	+= runtime-offset.o
pbl-y	+= runtime-offset.o
obj-$(CONFIG_ARM_OPTIMZED_STRING_FUNCTIONS)	+= memcpy.o
obj-$(CONFIG_ARM_OPTIMZED_STRING_FUNCTIONS)	+= memset.o
obj-$(CONFIG_ARM_UNWIND) += unwind.o
obj-$(CONFIG_MODULES) += module.o
extra-y += barebox.lds

pbl-y	+= lib1funcs.o
pbl-y	+= ashldi3.o
pbl-y	+= div0.o
